### ISSUE TITLE
Generate installable packages for Haiku

### ISSUE THREAD

**Issue by lorglas** [ArneSchwettmann/ArnesBreakout#2]
Hello, love2d is available on Haiku. We at BeSly have a question. May we pack your games in an installable package. We won't make any changes, your copyright will remain. The only thing we do is to pack the Love file into an HPKG (similar to Ubuntu's packages), which contains the dependency on Love2d, as well as your information about the game, copyright, etc. We would then host it on our repo and send it directly to you Send a link that you can then insert.

We would be happy to receive positive news.

Regards Lorglas
(Lorenz Glaser / BeSly)

**Comment by ArneSchwettmann** [comment]
Hello,
Yes that would be great, I would be honored if my little games were included in the project. Just keep in mind that the games don’t work with the latest version of love2d, so that might be an issue.

Please tell me if you need anything else from me.

Regards,
Arne

**Comment by lorglas** [comment]
Hi, on Haiku is only 11.2 available. Can you update your games to 11.2.

Thank you

**Comment by rsn8887** [comment]
I updated the source code to 11.3, can you test it?

**Comment by ArneSchwettmann** [comment]
I updated the source code to 11.3, can you test?

**Comment by ArneSchwettmann** [comment]
Here are the Love 11.3 compatible .love files:

https://www.arneschwettmann.com/ArnesBreakout_v21_Love.love
https://www.arneschwettmann.com/ArnesSpaceTaxi_v21_Love.love

I will make a proper release when I have more time.

**Comment by lorglas** [comment]
Both are Working. One little issue. The steering with mouse in the breakout game is not so easy. Can you optimize the speed of the mouse, or add a keyboard Steering?

**Comment by rsn8887** [comment]
It seems to depend on resolution of the screen and/or mouse. I will try to add an adjustment with plus/minus key. Keyboard is occupied for second player already.

**Comment by ArneSchwettmann** [comment]
Thank you for the feedback. It seems to depend on the resolution of the screen and/or mouse. On some machines it is fast, on others it is too slow. I will try to add an adjustment with plus/minus key or so. Keyboard is already occupied for player two controls.

**Comment by ArneSchwettmann** [comment]
I increased the default mouse sensitivity. I also added a mouse sensitivity option, via 's' key. See title screen. Here is the upated .love file:

https://www.arneschwettmann.com/ArnesBreakout_v21beta_Love.love

**Comment by ArneSchwettmann** [comment]
Fixed with v21

**Comment by lorglas** [comment]
ok, it's a little bit better. I tested it with two player and the steering for the 2 player is better. I set my system Mouse setting to the lowest speed and it make more fun. can you add for the first player keyboard control also.
Keyboard keys
WASD or ESDF

**Comment by rsn8887** [comment]
Ok I will do that

**Comment by ArneSchwettmann** [comment]
Ok I implemented wasd + ctrl for player 1. I will make a new release soon, after some more testing. I also added a smaller mouse sensitivity (1 now is more like 0.5 of what it was before).

**Comment by ArneSchwettmann** [comment]
I made a new release, v23. This should now hopefully fix all the issues mentioned here.

**Comment by lorglas** [comment]
Hi, with the extra keyboard steering for player one it makes fun. Thank you. 

I sent you an email.

Issue can be closed.

**Comment by ArneSchwettmann** [comment]
Great! Thanks!
